name: teste_flutter_firebase
description: "Teste Pratico Utilizando Flutter e Firebase."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # app
  bloc: ^9.0.0
  vibration: ^3.1.3
  share_plus: ^10.1.4
  flutter_bloc: 9.1.0
  url_launcher: ^6.3.1
  flutter_svg: ^2.0.17
  fluttertoast: ^8.2.12
  cupertino_icons: ^1.0.8
  tutorial_coach_mark: ^1.2.13
  smooth_page_indicator: ^1.2.1

  # data
  dio: ^5.8.0+1
  dartz: ^0.10.1

  # domain
  crypto: ^3.0.6
  local_auth: ^2.3.0
  flutter_modular: ^6.3.4
  connectivity_plus: ^6.1.3

  # Firebase
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.6
  firebase_analytics: ^11.4.5
  firebase_crashlytics: ^4.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  mocktail: ^1.0.4

flutter:
  uses-material-design: true
