name: teste_flutter_firebase
description: "Teste Pratico Utilizando Flutter e Firebase."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # app
  vibration: ^3.1.3
  url_launcher: ^6.3.1
  fluttertoast: ^8.2.12
  cupertino_icons: ^1.0.8
  shimmer_animation: ^2.2.2

  # data
  dio: ^5.8.0+1
  local_auth: ^2.3.0

  # domain
  dartz: ^0.10.1
  crypto: ^3.0.6
  flutter_modular: ^6.3.4
  shared_preferences: ^2.5.3

  # Firebase
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.6
  firebase_analytics: ^11.4.5
  firebase_crashlytics: ^4.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  mocktail: ^1.0.4

flutter:
  uses-material-design: true
